stages:
 - test

test:crate:
  image: ekidd/rust-musl-builder:nightly
  stage: test
  script:
    - rustup component add rustfmt --toolchain nightly
    - cargo fmt --all -- --check
    - cargo build
    - cargo test
  only:
    - branches
